import { DatasetOverview } from "./types";

export const sampleDatasets: { name: string; description: string; data: DatasetOverview }[] = [
  {
    name: "SaaS Sales Tracker",
    description: "Multi-regional sales metrics, revenue stats, product lines, and profit performance.",
    data: {
      fileName: "saas_sales_tracker.csv",
      rowCount: 140,
      colCount: 5,
      headers: ["Region", "ProductLine", "Revenue", "Profit", "SatisfiedCustomers"],
      columnStats: [
        {
          name: "Region",
          type: "string",
          missingCount: 0,
          sampleValues: ["North America", "Europe", "Asia-Pacific", "Latin America"],
          uniqueCount: 4,
          topCategories: [
            { category: "North America", count: 45 },
            { category: "Europe", count: 40 },
            { category: "Asia-Pacific", count: 35 },
            { category: "Latin America", count: 20 },
          ],
        },
        {
          name: "ProductLine",
          type: "string",
          missingCount: 0,
          sampleValues: ["Cloud ERP", "Premium Suite", "Security Vault", "API Gateway"],
          uniqueCount: 4,
          topCategories: [
            { category: "Cloud ERP", count: 50 },
            { category: "Premium Suite", count: 42 },
            { category: "Security Vault", count: 30 },
            { category: "API Gateway", count: 18 },
          ],
        },
        {
          name: "Revenue",
          type: "numeric",
          missingCount: 0,
          min: 1200,
          max: 18500,
          avg: 9420.5,
          sum: 1318870,
          sampleValues: ["4500", "12000", "8500", "3200", "15400"],
          distribution: [
            { label: "1.2k - 4.6k", count: 35 },
            { label: "4.6k - 8.1k", count: 42 },
            { label: "8.1k - 11.5k", count: 28 },
            { label: "11.5k - 15.0k", count: 20 },
            { label: "15.0k - 18.5k", count: 15 },
          ],
        },
        {
          name: "Profit",
          type: "numeric",
          missingCount: 3,
          min: -450,
          max: 9200,
          avg: 3845.2,
          sum: 526792,
          sampleValues: ["1200", "4300", "3100", "-150", "6400"],
          distribution: [
            { label: "-450 - 1.4k", count: 15 },
            { label: "1.4k - 3.3k", count: 45 },
            { label: "3.3k - 5.2k", count: 52 },
            { label: "5.2k - 7.1k", count: 20 },
            { label: "7.1k - 9.2k", count: 8 },
          ],
        },
        {
          name: "SatisfiedCustomers",
          type: "numeric",
          missingCount: 0,
          min: 15,
          max: 480,
          avg: 215.4,
          sum: 30156,
          sampleValues: ["150", "320", "280", "45", "410"],
          distribution: [
            { label: "15 - 108", count: 22 },
            { label: "108 - 201", count: 54 },
            { label: "201 - 294", count: 38 },
            { label: "294 - 387", count: 18 },
            { label: "387 - 480", count: 10 },
          ],
        },
      ],
      previewRows: [
        { _rowId: "1", Region: "North America", ProductLine: "Cloud ERP", Revenue: "15450", Profit: "6200", SatisfiedCustomers: "340" },
        { _rowId: "2", Region: "Europe", ProductLine: "Premium Suite", Revenue: "12300", Profit: "4900", SatisfiedCustomers: "280" },
        { _rowId: "3", Region: "Asia-Pacific", ProductLine: "Security Vault", Revenue: "8900", Profit: "3100", SatisfiedCustomers: "190" },
        { _rowId: "4", Region: "North America", ProductLine: "API Gateway", Revenue: "4200", Profit: "1200", SatisfiedCustomers: "95" },
        { _rowId: "5", Region: "Latin America", ProductLine: "Cloud ERP", Revenue: "3500", Profit: "-120", SatisfiedCustomers: "45" },
        { _rowId: "6", Region: "Europe", ProductLine: "Cloud ERP", Revenue: "14800", Profit: "5900", SatisfiedCustomers: "310" },
        { _rowId: "7", Region: "Asia-Pacific", ProductLine: "Premium Suite", Revenue: "11500", Profit: "4600", SatisfiedCustomers: "250" },
        { _rowId: "8", Region: "Latin America", ProductLine: "Security Vault", Revenue: "6100", Profit: "1800", SatisfiedCustomers: "120" },
      ],
      aiSynthesis: {
        summary: "This dataset tracks international SaaS operational performance, measuring Regional revenues, product tier profit metrics, and total happy customer scores. Standard region metrics are heavily weighted toward North American and European Cloud ERP implementations.",
        keyInsights: [
          "Cloud ERP constitutes over 42% of global volume and boasts the highest overall profit boundaries across all divisions.",
          "Satisfied customers positively correlate with high profit margins, especially in mature regional quarters.",
          "Asia-Pacific security vault items represents a robust growing market segment with very minimal client churn indices.",
        ],
        potentialAnomalies: [
          "Latin American Cloud ERP items indicated negative profit margins (-$120), indicating high customer acquisition costs.",
        ],
        suggestedQuestions: [
          "Which product lines generate the highest average revenues?",
          "Can you explain why Latin America Cloud ERP results in a negative profit margin?",
          "What is the average customer response score per region?",
        ],
      },
    },
  },
  {
    name: "Climate Temperature Tracker",
    description: "Climatology averages, temperature differentials, weather stations activity records.",
    data: {
      fileName: "global_climatology_tracker.csv",
      rowCount: 90,
      colCount: 4,
      headers: ["StationName", "AverageTemperature", "Altitude", "WindSpeed"],
      columnStats: [
        {
          name: "StationName",
          type: "string",
          missingCount: 0,
          sampleValues: ["Vinci Depot", "Base Green", "Siberia Polar II", "Amazon Core"],
          uniqueCount: 4,
          topCategories: [
            { category: "Vinci Depot", count: 30 },
            { category: "Base Green", count: 25 },
            { category: "Siberia Polar II", count: 20 },
            { category: "Amazon Core", count: 15 },
          ],
        },
        {
          name: "AverageTemperature",
          type: "numeric",
          missingCount: 0,
          min: -42.5,
          max: 48.0,
          avg: 12.8,
          sum: 1152,
          sampleValues: ["14.2", "22.5", "-31.0", "38.5"],
          distribution: [
            { label: "-42.5 to -24.4", count: 15 },
            { label: "-24.4 to -6.3", count: 10 },
            { label: "-6.3 to 11.8", count: 25 },
            { label: "11.8 to 29.9", count: 30 },
            { label: "29.9 to 48.0", count: 10 },
          ],
        },
        {
          name: "Altitude",
          type: "numeric",
          missingCount: 0,
          min: 12,
          max: 4200,
          avg: 1045,
          sum: 94050,
          sampleValues: ["50", "420", "1500", "2800", "3400"],
          distribution: [
            { label: "12 - 849", count: 42 },
            { label: "849 - 1687", count: 28 },
            { label: "1687 - 2525", count: 12 },
            { label: "2525 - 3362", count: 5 },
            { label: "3362 - 4200", count: 3 },
          ],
        },
        {
          name: "WindSpeed",
          type: "numeric",
          missingCount: 2,
          min: 1.2,
          max: 88.5,
          avg: 24.5,
          sum: 2205,
          sampleValues: ["12.5", "5.4", "48.2", "72.0", "8.2"],
          distribution: [
            { label: "1.2 - 18.6", count: 38 },
            { label: "18.6 - 36.1", count: 32 },
            { label: "36.1 - 53.5", count: 12 },
            { label: "53.5 - 71.0", count: 6 },
            { label: "71.0 - 88.5", count: 2 },
          ],
        },
      ],
      previewRows: [
        { _rowId: "1", StationName: "Vinci Depot", AverageTemperature: "14.2", Altitude: "150", WindSpeed: "12.5" },
        { _rowId: "2", StationName: "Base Green", AverageTemperature: "22.5", Altitude: "420", WindSpeed: "5.4" },
        { _rowId: "3", StationName: "Siberia Polar II", AverageTemperature: "-31.0", Altitude: "1500", WindSpeed: "48.2" },
        { _rowId: "4", StationName: "Amazon Core", AverageTemperature: "38.5", Altitude: "50", WindSpeed: "8.2" },
        { _rowId: "5", StationName: "Base Green", AverageTemperature: "21.0", Altitude: "450", WindSpeed: "6.1" },
        { _rowId: "6", StationName: "Vinci Depot", AverageTemperature: "16.5", Altitude: "130", WindSpeed: "10.4" },
        { _rowId: "7", StationName: "Siberia Polar II", AverageTemperature: "-28.5", Altitude: "1480", WindSpeed: "35.0" },
      ],
      aiSynthesis: {
        summary: "This climatic tracker aggregates temperature and meteorological details across key international base camps. Altitude variance provides interesting patterns.",
        keyInsights: [
          "Siberia Polar II demonstrates high altitude wind currents, averaging extreme velocity scores above 48 km/h.",
          "Average temperature behaves as an inverse correlate to base camp altitude as predicted by barometric profiles.",
        ],
        potentialAnomalies: [
          "Amazon base camp reports occasional heat spikes (48.0°C) which should be correlated with surrounding environmental records.",
        ],
        suggestedQuestions: [
          "How does altitude correlate with average meteorological wind trends?",
          "What is the average wind speed measured across low-altitude weather camps?",
        ],
      },
    },
  },
];
